=== ZiShanShi/designer/WebRoot/WEB-INF/config/sql.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT sqls (dataSpace*)+>
<!ATTLIST sqls
	xmlns:fo CDATA #IMPLIED
	namespace CDATA #IMPLIED
	active (true|false) #IMPLIED
>

<!ELEMENT dataSpace (sql*)+>
<!ATTLIST dataSpace
	name CDATA #IMPLIED
>

<!ELEMENT sql (#PCDATA|condition)*>
<!ATTLIST sql
	name CDATA #REQUIRED
	timeout CDATA #IMPLIED
>

<!ELEMENT condition (#PCDATA)>
<!ATTLIST condition
	value CDATA #REQUIRED
>

=== ZiShanShi/designer/out/artifacts/designer_war_exploded/WEB-INF/sql/dataobject.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sql PUBLIC "sql" "../config/sql.dtd" >
	
<sqls>
	<dataSpace name="system_default">
		<sql name="insert">
			insert into @{tablename} (@{fieldNames}) values(@{fieldValues})
		</sql>
	  
		<sql name="deleteById">
			delete from @{tablename} where id = '@{id}'
		</sql>
	  
		<sql name="deleteByCriteria">
			delete from @{tablename} where @{filter} 
		</sql>
		
		<sql name="truncateTable">
			TRUNCATE table  @{tableName};
		</sql>

		<sql name="updateById">
			update @{tablename} set @{fieldNameValues} where @{fieldNameId} = @{id}
		</sql>
		
		<sql name="updateByCriteria">
			update @{tablename} set @{entity} where @{filter}
		</sql>
		
		<sql name="getLineById">
			select * from @{tablename} where @{fieldNameId} = @{id}
		</sql>
	
		<sql name="getDataSet">
			select * from @{tablename} where @{filter}
		</sql>
		
		<sql name="getFieldsDataSet">
			select @{fieldNames} from @{tablename} where @{filter}
		</sql>
		
		<sql name="getDataByPage_MySQL">
			<![CDATA[
				select * from (@{sql})temp_table limit @{beginno}, @{pagesize}
			]]>
		</sql>
		
		<sql name="getDataByPage_SqlServer">
			<![CDATA[
			select * from (
				select 
					row_number() OVER(ORDER BY @{orderby}) as rowno,
					temp_table.*
					from (@{sql})temp_table
				) temp_table2
			where rowno > @{beginno} and rowno <= @{endno}
			]]>
		</sql>
		
		<sql name="getDataGroupby">
			SELECT @{fields} FROM @{tablename} GROUP BY @{groupby};
		</sql>	
		
		<sql name="getCount2">
			select count(1) from (@{sql})temp_table
		</sql>	
		
		<sql name="getCount">
			select count(1) from @{tablename} where @{filter}
		</sql>		
		
		<sql name="getTree">
			select * from @{tablename} where @{filter} order by parentId
		</sql>
		
		<sql name="getCountOfId">
			select count(1) from @{tablename} where id = @{id}
		</sql>
		
		<sql name="batchInsert">
			insert into @{tablename} (@{fieldNames}) values(@{placeHolders})
		</sql>	
		
		<sql name="updatetableactive">
			update @{table} set @{field} = '@{active}' where @{filter}
		</sql>
	</dataSpace>

</sqls>

=== ZiShanShi/designer/out/artifacts/designer_war_exploded/WEB-INF/sql/rebate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql PUBLIC "sql" "../config/sql.dtd" >

<sqls>

	<dataSpace name="mainelement">
		<sql name="getFormulaMainElement">
			<![CDATA[
				SELECT
				ele.element, famap.agreement_type as agreementtype, elemap.type, famap.agreement_table as tablename,elemap.agreement_field as fieldname, elemap.sql_name as sqlname
				FROM rebate_element_map  elemap
				LEFT JOIN rebate_formula_element  ele  ON ele.id = elemap.formula_elementid
				LEFT JOIN rebate_formula_agreement_map famap on famap.id = elemap.formula_map_id				
			]]>
		</sql>
		
		<sql name="getFormulaByResult">
			<![CDATA[
				SELECT * from rebate_formula WHERE result = '@{result}';
			]]>
		</sql>
		
		<sql name="getFormulaAgreementMap">
			<![CDATA[
				SELECT * FROM `rebate_formula_agreement_map` fam
				LEFT JOIN rebate_formula f on f.id = fam.formula_id where active = 'T';
			]]>
		</sql>
		
		<sql name="getAgreementByTableNameAndType">
			<![CDATA[
				select *  from @{tablename} where typecode = '@{type}'
			]]>
		</sql>
		
		<sql name="getAgreementByTableName">
			<![CDATA[
				select * from @{tablename}
			]]>
		</sql>
	</dataSpace>	
	
	<dataSpace name="caluclate">
		<sql name="insertMonthFlowAgreementMap">
			<![CDATA[
				insert into rebate_process (id, flowid, agreementid)
			]]>
		</sql>
		
		<sql name="getReceivableMoney">
			<![CDATA[
				select 60 from agreement where id = '@{id}';
			]]>
		</sql>
		
		<sql name="getInventory">
			<![CDATA[
				select 80 from agreement where id = '@{id}';
			]]>
		</sql>
		
		<sql name="getKPISum">
			<![CDATA[
				SELECT count(1) from agreement a
				LEFT JOIN salesflow on salesflow.dealercode = a.businesscode
				WHERE a.id = '@{id}'
				and year(a.begindate) <= salesflow.`year` and  year(a.enddate) >= salesflow.`year`
				and month(a.begindate) <= salesflow.`month`
				and month(a.enddate) >= salesflow.`month`
			]]>
		</sql>
		
	</dataSpace>	
	
	
</sqls>

=== ZiShanShi/designer/WebRoot/WEB-INF/sql/system.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql PUBLIC "sql" "../config/sql.dtd" >

<sqls>

	<dataSpace name="user">
		<sql name="getClientUserByPhoneOrName">
			<![CDATA[
				select * from usr where email = '@{email}' or name = '@{username}' and  usr.active = 'T'
			]]>
		</sql>

		<sql name="getUser">
			select usr.id, usr.name, usr.type, usr.caption, usr.phone, usr.rolecode, usr.title, usr.password,
				org.code as orgcode, org.name as orgname, org.name as orgenname, org.id as orgid,
				'' as emp_id, usr.caption as emp_name, '' as emp_enname,
				'' as emp_title, '' as emp_entitle, 
				'' as emp_department, '' as emp_endepartment,
				'' as emp_position
				from usr 
				left join usrorg on usr.id = usrorg.userid
				left join org on usrorg.orgid = org.id
			where usr.active = 'T'
				and @{userfilter} @{orgfilter}
		</sql>
	</dataSpace>	
	
	<dataSpace name="menu">
		<sql name="getRootMenu" > 
			select * from menu where menu.id in (select menuid from roleauthority where rolecode = '@{rolecode}') and parentId is null order by orderno
		</sql>

		<sql name="getMenuTreeByRoot" > 
			select * from menu 
			where menu.id in (select menuid from roleauthority where rolecode = '@{rolecode}') and rootId = '@{rootid}' 
			order by grade, parentId, orderno
		</sql>
	</dataSpace>
	
	<dataSpace name="treeitory">
		<sql name="getemployeeid" > 
			select id , parentid
			from employee 
		</sql>	
		
		<sql name="getparentidfromemployee" > 
			select parentid
			from employee  where id = '@{id}'
		</sql>
			
		<sql name="getgrandparentidfromemployee" > 
			select grandpaid
			from employee  where id = '@{id}'
		</sql>	
		
	</dataSpace>
	
</sqls>

=== ZiShanShi/designer/out/artifacts/designer_war_exploded/WEB-INF/sql/dictionary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sql PUBLIC "sql" "../config/sql.dtd" >

<sqls>

	<dataSpace name="dictionary">
		<sql name="getDictionary" > 
			select * from dictionary order by groupcode, value
		</sql>

		<sql name="getOneDictionary" > 
			select * from dictionary where groupcode = '@{groupcode}' order by code
		</sql>
		
	</dataSpace>
	
	<dataSpace name="other">
		<sql name="getGeneralRebateBook" > 
			select * from v_generalrebatebook where typecode = @{typecode} and @{filter} 
		</sql>
		
		<sql name="getPlatform" > 
			select customer.* from customer where typecode = 'platform' and @{filter} order by name
		</sql>
		
		<sql name="getBusinessList" > 
			select customer.* from customer where typecode = 'business' and @{filter}
		</sql>
		
		<sql name="getAgentList" > 
			select id as agentId, name as agentName, customer.* from customer where typecode = 'agent' and @{filter}
		</sql>
		
		<sql name="getCustomerList" > 
			select customer.* from customer where typecode = 'hospital' and @{filter}
		</sql>
			
		<sql name="getProvinceList" > 
			select cnname as code, cnname as name from province order by name
		</sql>	
		
		<sql name="getProductList" > 
			select product.*, product.price as price_sale  from product where @{filter}
		</sql>	
		
		<sql name="getPaymentorgList" > 
			select cspname as code, cspname as name from csolist order by name
		</sql>	
		
		<sql name="getMyRebateslit" > 
			select rebateslit.id, rebateslit.docyear, rebateslit.docmonth, rebateslit.statuscode, rebateslit.no, rebateslit.typecode, rebateslit.createtime,rebateslit.workflowid, 
			customer.code as agentcode, customer.name as agentname, customer.id as agentid, rebateslit.operator,
			(select sum(rebatedetail.qty) from rebatedetail where rebatedetail.parentid = rebateslit.id) as qty_sum,
			(select sum(rebatedetail.price_rebate) from rebatedetail where rebatedetail.parentid = rebateslit.id) as sumprice_rebate 
			from rebateslit 
			left join customer on agentid = customer.id 
			where operatorid in (SELECT id from v_hierarchy where id = '@{userid}' or parentid = '@{userid}') and @{filter} 
		</sql>	
		
		<sql name="getApprovalRebateslit" > 
			select rebateslit.id, rebateslit.statuscode, rebateslit.no, rebateslit.typecode, rebateslit.createtime,
			customer.code as agentcode, customer.name as agentname, customer.id as agentid,
			(select sum(rebatedetail.qty) from rebatedetail where rebatedetail.parentid = rebateslit.id) as qty_sum,
			(select sum(rebatedetail.price_rebate) from rebatedetail where rebatedetail.parentid = rebateslit.id) as sumprice_rebate,
			v_hierarchy.name as operator 
			from rebateslit 
			left join customer on agentid = customer.id 
			left join v_hierarchy on operatorid = v_hierarchy.id 
			where @{filter} 
		</sql>	
		
		<sql name="getMyRebateDetail" > 
			select rebatedetail.id, rebatedetail.flowid, rebatedetail.price_rebate, rebatedetail.flowyear, rebatedetail.flowmonth, rebatedetail.qty_original, rebatedetail.qty,
			customer.code as customercode, customer.name as customername, product.name as productname, product.spec, generalrebatebook.qty_available
			from rebatedetail
			left join customer on customerid = customer.id 
			left join generalrebatebook on flowid = generalrebatebook.id 
			left join product on rebatedetail.productid = product.id 
			where rebatedetail.parentid = '@{parentid}' 
		</sql>	
		
		<sql name="getRebateRecord" > 
			select RebateRecord.*, csolist.agentname, csolist.customername, csolist.cspname, csolist.bankname, csolist.accountno
			from rebaterecord
			left join rebateslit on rebateslitid = rebateslit.id 
			left join csolist on csolistid = csolist.id 
			where rebateslitid = '@{rebateslitid}' 
		</sql>	
		
	</dataSpace>
	
</sqls>
